name: Build React Native

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:latest

    steps:
    - name: Free disk space
      run: |
        echo 'Disk space before cleanup'
        df -aH
        sudo apt-get remove -y --purge '^mysql-.*' '^mongodb-.*' '^postgresql-.*' '^aspnetcore-*' '^dotnet-.*' '^php.*-.*' 'mono-complete' 
        sudo apt-get autoremove -y
        sudo rm -rf /usr/share/dotnet
        echo 'Showing Android SDKs'
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall 'ndk;24.0.8215888' 'ndk;25.2.9519653'
        echo 'Removing all Docker images'
        docker rmi -f $(docker images -aq)
        echo 'Disk space after cleanup'
        df -aH

    - name: Checkout react-native
      uses: actions/checkout@v3
      with:
        repository: facebook/react-native
        ref: v0.72.4

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Apply utf8-fix.patch
      run: |
        curl -fsSL https://github.com/facebook/react-native/commit/011075f722932b2a12de0db01d5c880aae4e4473.patch -o utf8-fix.patch
        git apply utf8-fix.patch

    - name: Install dependencies
      run: yarn install

    - name: Build and install archives
      run: ./gradlew installArchives
      
    - name: Move output and clean up
      run: |
        mv ./packages/react-native/android ../android
        cd ..
        rm -rf react-native-build
      
    - name: Compress android output
      run: tar -czf android.tar.gz android

    - name: Upload android output artifact
      uses: actions/upload-artifact@v3
      with:
        name: android.tar.gz
        path: android.tar.gz
        
