name: Build React Native

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:latest

    steps:
    - name: Checkout react-native
      uses: actions/checkout@v3
      with:
        repository: facebook/react-native
        ref: v0.72.0

    - name: Apply utf8-fix.patch
      run: |
        curl -fsSL https://github.com/facebook/react-native/commit/011075f722932b2a12de0db01d5c880aae4e4473.patch -o utf8-fix.patch
        git apply utf8-fix.patch

    - name: Install dependencies
      run: yarn install

    - name: Build and install archives
      run: ./gradlew installArchives
      
    - name: Compress android output
      run: |
        tar -czf android.tar.gz ./packages/react-native/android

    - name: Upload android output artifact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: android.tar.gz
        
